# Generated by Django 4.1.2 on 2022-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'Order Confirmed'), ('3', 'Shipped'), ('4', 'Out For Delivery\t'), ('5', 'Delivered')], default='pending', max_length=20),
        ),
    ]
